### ISSUE TITLE
Course Page

### ISSUE THREAD

**Issue by TonyRays** [MSSE-research-projects/gamification-platform#7]
Issues on course list page:
- [x] Students and TAs cannot view courses they didn't register for.
- [x] Instructors, TAs and students should be able to see different number of buttons for each course. For example, instructors have 'delete' button that TAs and students don't have, TAs have 'edit' button that students dont' have.

Issues on course edit page:
- [x] Return 404 when input wrong URL

Issues on course detail page:
- [x] Web page is too narrow in view page.
- [x] may add a line between header and syllabus in view page.(like Canvas)
- [ ] MAY make it possible to add hyperlink in syllabus in the future.(like Canvas)
- [x] add a Back button on course view page

Issues on course member page:
- [x] Adding an instructor or a TA will also create an instance in Entity table. This should only happen when adding new students.
- [x] Delete student membership in a team when changing his role from Student to TA.

Models:
- [x] Refactor `Course.teams` property.
- [x] Add tests for `Course.teams` property.
- [x] In `Course.get_query` helper function, add checks for parameter `role`.
- [x] Add tests for `Course.get_query` function.

> Note: The naming convention of constant values is all capital letters like `INSTRUCTOR` instead of `Instructor`.

**Comment by TonyRays** [comment]
- [ ] delete button and members button do not work properly and return "column entities.course_id does not exist"

- [ ] Web page is too narrow in view page.

- [ ] may add a line between header and syllabus in view page.(like Canvas)

- [ ] MAY make it possible to add hyperlink in syllabus in the future.(like Canvas)

**Comment by prime51** [comment]
Since we now have a foreign key from team to course, we can refactor Course.teams property as followed:
```python
@property
def teams(self):
    return Team.objects.filter(course=self)
```
